apiVersion: v1 
kind: Service 
metadata: 
  name: prometheus
  labels:
    app: strimzi
spec: 
  ports: 
    - port: 9090
      protocol: TCP
      targetPort: http
  selector: 
    app.kubernetes.io/name: prometheus-operator
  sessionAffinity: None
  type: LoadBalancer
