---
version: '3'

services:
  k9s:
    image: entechlog/kube-tools${KUBE_TOOLS_VERSION_TAG}
    container_name: k9s
    build:
      context: ./docker/
      args:
        OCTANT_VERSION: ${OCTANT_VERSION}
        K9S_VERSION: ${K9S_VERSION}
    command: 
      - bash 
      - -c 
      - |
        echo "Launching k9s"
        sleep infinity
    restart: on-failure
    volumes:
      - ./.kube/config:/.kube/config
    environment:
      - KUBECONFIG=/.kube/config
      - TERM=xterm-256color
